services:
  - type: web
    name: train-tickets-provider
    env: docker
    repo: https://github.com/kuhalgore/train_tickets_availl_provider
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: SMTP_USER
      - key: SMTP_PASS
      - key: PORT
        value: 18080
